module(
    name = "antlr4_opt_examples",
    version = "0.0.0",
    compatibility_level = 1,
)

## Use rules_antlr from parent folder
bazel_dep(name = "rules_antlr", version = "0.0.0")
local_path_override(
    module_name = "rules_antlr",
    path = "../..",
)

antlr_extension = use_extension("@rules_antlr//antlr:extensions.bzl", "antlr_extension")
antlr_extension.optimized_toolchain(version = "4.7.4")
use_repo(
    antlr_extension,
    "antlr3_runtime",
    "antlr4_runtime",
    "antlr4_tool",
    "javax_json",
    "stringtemplate4",
)

## Third party dependencies
bazel_dep(name = "platforms", version = "0.0.10")
bazel_dep(name = "rules_java", version = "8.6.1")
