name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "LICENSE"
      - ".github/*.md"
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "LICENSE"
      - ".github/*.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK 11
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: zulu
          java-version: "11"

      - name: Verify Bazel installation
        run: bazelisk version

      - name: Build examples
        shell: bash
        run: |
          cd examples
          bazelisk build \
            --config ci \
            --config remote-cache \
            --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }} \
            //antlr2/Cpp/... \
            //antlr2/Calc/... \
            //antlr2/Python/... \
            //antlr3/Cpp/... \
            //antlr3/Java/... \
            //antlr3/Python2/... \
            //antlr3/Python3/... \
            //antlr4/Cpp/... \
            //antlr4/Go/... \
            //antlr4/Java/... \
            //antlr4/Python2/... \
            //antlr4/Python3/...

      - name: Build antlr4-opt
        shell: bash
        run: |
          cd examples/antlr4-opt
          bazelisk build \
            --config ci \
            --config remote-cache \
            --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }} \
            //...

      - name: Run tests
        shell: bash
        run: |
          bazelisk test \
            --config ci \
            --config remote-cache \
            --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }} \
            //...

      - name: Shutdown Bazel
        shell: bash
        run: bazelisk shutdown
