name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: "11"

      - name: Verify Bazel installation
        run: bazelisk version

      - name: Build examples
        run: |
          cd examples
          bazelisk build --config ci //antlr2/Cpp/... //antlr2/Calc/... //antlr2/Python/... //antlr3/Cpp/... //antlr3/Java/... //antlr3/Python2/... //antlr3/Python3/... //antlr4/Cpp/... //antlr4/Go/... //antlr4/Java/... //antlr4/Python2/... //antlr4/Python3/...

      - name: Build antlr4-opt
        run: |
          cd examples/antlr4-opt
          bazelisk build --config ci //...

      - name: Run tests
        run: |
          bazelisk test --config ci //...

      - name: Shutdown Bazel
        run: bazelisk shutdown
